#!/usr/bin/env python3
"""
Copyright (c) 2022, JRL-CARI CNR-STIIMA/UNIBS
Marco Faroni marco.faroni@polimi.it
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of the <organization> nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

from PIL import Image
import numpy as np
import yaml
from datetime import datetime

INPUT_IMAGE_PATH = "../input/images/maze.png"
FILENAME_OBJECT_GROUPS = "../output/object_groups_bitmap.yaml"
FILENAME_OBJECTS_DESCRIPTION = "../output/objects_description_bitmap.yaml"
SCENARIO_NAME = "maze_image"

RESOLUTION = 20, 20  # pixels
MAZE_SIZE = 1, 1   # meters
BOX_SIZE = MAZE_SIZE[0]/RESOLUTION[0], MAZE_SIZE[1]/RESOLUTION[1]
BOX_SIZE_MM = int(BOX_SIZE[0]*1000), int(BOX_SIZE[1]*1000)
BACKGROUND = True

if __name__ == '__main__':

    im = Image.open(INPUT_IMAGE_PATH)
    p = np.array(im)

    im_resized = im.resize(RESOLUTION, Image.ANTIALIAS)
    p = np.array(im_resized)
    print(p.shape)
    print(p)

    if BACKGROUND:
        idx_solid = np.where(p[:, :] == False)
        idx_transparent = np.where(p[:, :] == True)
    else:
        idx_solid = np.where(p[:, :, 3] > 127)
        p[idx_solid] = [0, 0, 0, 255]
        idx_transparent = np.where((p[:, :, 3] <= 127))
        p[idx_transparent] = [255, 255, 255, 255]

    # im_filtered = Image.fromarray(p)
    # im_filtered.save("compressed.png", "PNG")

    filepath = FILENAME_OBJECTS_DESCRIPTION
    file_obj = open(filepath, 'w')
    file_obj.truncate(0)  # delete all content
    file_obj.write('scene_autogenerated_on: ' + datetime.now().strftime('%m/%d/%Y, %H:%M:%S'))
    file_obj.close()

    box_name = 'box_' + str(BOX_SIZE_MM[0]) + 'x' + str(BOX_SIZE_MM[1]) + 'mm'
    box_element = {box_name: {'color': [0.7, 0.7, 0.7, 1], 'box': [BOX_SIZE[0], BOX_SIZE[1], 0.1], 'offset': [0.0, 0.0, 0.0]}}

    with open(filepath, 'r') as yamlfile:
        current_yaml = yaml.safe_load(yamlfile)  
        current_yaml.update({'object_geometries': box_element})

    if current_yaml:
        with open(filepath, 'w') as yamlfile:
            yaml.safe_dump(current_yaml, yamlfile)  

    filepath = FILENAME_OBJECT_GROUPS
    file_obj = open(filepath, 'w')
    file_obj.truncate(0)  # delete all content
    file_obj.write('scene_autogenerated_on: ' + datetime.now().strftime('%m/%d/%Y, %H:%M:%S'))
    file_obj.close()

    boxes = []
    for id_row, id_col in zip(idx_solid[0], idx_solid[1]):
        x = (0.5 + id_col) * BOX_SIZE[0]
        y = MAZE_SIZE[1] - (0.5 + id_row) * BOX_SIZE[1]
        box_i = {'type': box_name, 'frame': "world", 'position': [float(x), float(y), 0.0], 'quaternion': [0, 0, 0, 1]}
        boxes.append(box_i)

    print(idx_solid[0])
    print(idx_solid[1])

    with open(filepath, 'r') as yamlfile:
        current_yaml = yaml.safe_load(yamlfile) 
        new_box = {SCENARIO_NAME : boxes}
        current_yaml.update(new_box)

    if current_yaml:
        with open(filepath, 'w') as yamlfile:
            yaml.safe_dump(current_yaml, yamlfile)
